# Generated by Django 5.2.13 on 2026-04-17 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_transcription', models.TextField()),
                ('autism_score', models.FloatField()),
                ('severity_level', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('dimension_scores', models.JSONField(default=dict)),
                ('ai_analysis', models.TextField(blank=True)),
                ('key_observations', models.JSONField(default=list)),
                ('immediate_recommendations', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed by Psychologist'), ('corrected', 'Corrected by Psychologist')], default='pending', max_length=20)),
                ('psychologist_note', models.TextField(blank=True)),
                ('corrected_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='children.child')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
