# Generated by Django 5.2.13 on 2026-04-17 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('activity_type', models.CharField(choices=[('Eating', 'Eating'), ('Drinking', 'Drinking'), ('Writing', 'Writing'), ('Playing', 'Playing'), ('Communicating', 'Communicating'), ('Social Interaction', 'Social Interaction'), ('Repetitive Behaviors', 'Repetitive Behaviors'), ('Sensory Response', 'Sensory Response'), ('Drawing', 'Drawing'), ('Reading', 'Reading'), ('Other', 'Other')], max_length=50)),
                ('participant_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
