# Generated by Django 4.2.10 on 2026-05-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assessment_result', 'Assessment Result'), ('review_complete', 'Review Complete'), ('message', 'Message'), ('reminder', 'Reminder'), ('psychologist_report', 'Psychologist Report'), ('child_added', 'Child Added'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
