# Generated by Django 5.2.13 on 2026-05-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assessment_result', 'Assessment Result'), ('review_complete', 'Review Complete'), ('message', 'Message'), ('reminder', 'Reminder'), ('psychologist_report', 'Psychologist Report'), ('child_added', 'Child Added'), ('system', 'System'), ('announcement', 'Announcement')], default='system', max_length=30),
        ),
    ]
